// Mocks generated by Mockito 5.4.6 from annotations
// in home_ai_index/test/widget/screens/add_item_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i8;
import 'dart:ui' as _i9;

import 'package:home_ai_index/data/models/category.dart' as _i4;
import 'package:home_ai_index/data/models/location.dart' as _i2;
import 'package:home_ai_index/data/repositories/location_repository.dart'
    as _i10;
import 'package:home_ai_index/presentation/viewmodels/add_item_viewmodel.dart'
    as _i3;
import 'package:image_picker/image_picker.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocation_0 extends _i1.SmartFake implements _i2.Location {
  _FakeLocation_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AddItemViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddItemViewModel extends _i1.Mock implements _i3.AddItemViewModel {
  MockAddItemViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  List<_i4.Category> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: <_i4.Category>[],
          )
          as List<_i4.Category>);

  @override
  _i3.RecognitionState get recognitionState =>
      (super.noSuchMethod(
            Invocation.getter(#recognitionState),
            returnValue: _i3.RecognitionState.idle,
          )
          as _i3.RecognitionState);

  @override
  bool get hasApiCredentials =>
      (super.noSuchMethod(
            Invocation.getter(#hasApiCredentials),
            returnValue: false,
          )
          as bool);

  @override
  bool get usedOnlineRecognition =>
      (super.noSuchMethod(
            Invocation.getter(#usedOnlineRecognition),
            returnValue: false,
          )
          as bool);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  int get quantity =>
      (super.noSuchMethod(Invocation.getter(#quantity), returnValue: 0) as int);

  @override
  String get notes =>
      (super.noSuchMethod(
            Invocation.getter(#notes),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#notes),
            ),
          )
          as String);

  @override
  String get suggestedName =>
      (super.noSuchMethod(
            Invocation.getter(#suggestedName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#suggestedName),
            ),
          )
          as String);

  @override
  List<String> get alternativeLabels =>
      (super.noSuchMethod(
            Invocation.getter(#alternativeLabels),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get isLowConfidence =>
      (super.noSuchMethod(
            Invocation.getter(#isLowConfidence),
            returnValue: false,
          )
          as bool);

  @override
  String get recognitionSource =>
      (super.noSuchMethod(
            Invocation.getter(#recognitionSource),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#recognitionSource),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> loadCategories() =>
      (super.noSuchMethod(
            Invocation.method(#loadCategories, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> pickImage(_i7.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [source]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> recognizeImage(_i8.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#recognizeImage, [imageBytes]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> retryRecognition() =>
      (super.noSuchMethod(
            Invocation.method(#retryRecognition, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> confirmQuotaAndRecognize() =>
      (super.noSuchMethod(
            Invocation.method(#confirmQuotaAndRecognize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void cancelQuotaWarning() => super.noSuchMethod(
    Invocation.method(#cancelQuotaWarning, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> refreshCredentialsStatus() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCredentialsStatus, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> saveItem() =>
      (super.noSuchMethod(
            Invocation.method(#saveItem, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void setName(String? value) => super.noSuchMethod(
    Invocation.method(#setName, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setCategory(String? value) => super.noSuchMethod(
    Invocation.method(#setCategory, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setLocation(String? value) => super.noSuchMethod(
    Invocation.method(#setLocation, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setQuantity(int? value) => super.noSuchMethod(
    Invocation.method(#setQuantity, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setNotes(String? value) => super.noSuchMethod(
    Invocation.method(#setNotes, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedImagePath(String? value) => super.noSuchMethod(
    Invocation.method(#setSelectedImagePath, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setErrorMessage(String? value) => super.noSuchMethod(
    Invocation.method(#setErrorMessage, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i10.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.Location>> getLocations({bool? rootOnly = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getLocations, [], {#rootOnly: rootOnly}),
            returnValue: _i6.Future<List<_i2.Location>>.value(<_i2.Location>[]),
          )
          as _i6.Future<List<_i2.Location>>);

  @override
  _i6.Future<_i2.Location> getLocationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationById, [id]),
            returnValue: _i6.Future<_i2.Location>.value(
              _FakeLocation_0(this, Invocation.method(#getLocationById, [id])),
            ),
          )
          as _i6.Future<_i2.Location>);

  @override
  _i6.Future<List<_i2.Location>> getChildLocations(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#getChildLocations, [parentId]),
            returnValue: _i6.Future<List<_i2.Location>>.value(<_i2.Location>[]),
          )
          as _i6.Future<List<_i2.Location>>);

  @override
  _i6.Future<List<_i2.Location>> getLocationPath(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationPath, [locationId]),
            returnValue: _i6.Future<List<_i2.Location>>.value(<_i2.Location>[]),
          )
          as _i6.Future<List<_i2.Location>>);

  @override
  _i6.Future<_i2.Location> createLocation(_i2.Location? location) =>
      (super.noSuchMethod(
            Invocation.method(#createLocation, [location]),
            returnValue: _i6.Future<_i2.Location>.value(
              _FakeLocation_0(
                this,
                Invocation.method(#createLocation, [location]),
              ),
            ),
          )
          as _i6.Future<_i2.Location>);

  @override
  _i6.Future<_i2.Location> updateLocation(_i2.Location? location) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocation, [location]),
            returnValue: _i6.Future<_i2.Location>.value(
              _FakeLocation_0(
                this,
                Invocation.method(#updateLocation, [location]),
              ),
            ),
          )
          as _i6.Future<_i2.Location>);

  @override
  _i6.Future<bool> deleteLocation(String? id, {bool? deleteItems = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteLocation,
              [id],
              {#deleteItems: deleteItems},
            ),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> hasItems(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#hasItems, [locationId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> validateLocationMove(
    String? locationId,
    String? newParentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateLocationMove, [locationId, newParentId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
