// Mocks generated by Mockito 5.4.6 from annotations
// in home_ai_index/test/widget/screens/add_item_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;
import 'dart:ui' as _i8;

import 'package:home_ai_index/data/models/category.dart' as _i3;
import 'package:home_ai_index/presentation/viewmodels/add_item_viewmodel.dart'
    as _i2;
import 'package:image_picker/image_picker.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AddItemViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddItemViewModel extends _i1.Mock implements _i2.AddItemViewModel {
  MockAddItemViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  List<_i3.Category> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: <_i3.Category>[],
          )
          as List<_i3.Category>);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  int get quantity =>
      (super.noSuchMethod(Invocation.getter(#quantity), returnValue: 0) as int);

  @override
  String get notes =>
      (super.noSuchMethod(
            Invocation.getter(#notes),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#notes),
            ),
          )
          as String);

  @override
  String get suggestedName =>
      (super.noSuchMethod(
            Invocation.getter(#suggestedName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#suggestedName),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> loadCategories() =>
      (super.noSuchMethod(
            Invocation.method(#loadCategories, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> pickImage(_i6.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [source]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recognizeImage(_i7.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#recognizeImage, [imageBytes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> saveItem() =>
      (super.noSuchMethod(
            Invocation.method(#saveItem, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void setName(String? value) => super.noSuchMethod(
    Invocation.method(#setName, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setCategory(String? value) => super.noSuchMethod(
    Invocation.method(#setCategory, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setLocation(String? value) => super.noSuchMethod(
    Invocation.method(#setLocation, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setQuantity(int? value) => super.noSuchMethod(
    Invocation.method(#setQuantity, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setNotes(String? value) => super.noSuchMethod(
    Invocation.method(#setNotes, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedImagePath(String? value) => super.noSuchMethod(
    Invocation.method(#setSelectedImagePath, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setErrorMessage(String? value) => super.noSuchMethod(
    Invocation.method(#setErrorMessage, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
