// Mocks generated by Mockito 5.4.6 from annotations
// in home_ai_index/test/widget/screens/search_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:home_ai_index/data/models/item.dart' as _i4;
import 'package:home_ai_index/data/repositories/item_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemRepository extends _i1.Mock implements _i2.ItemRepository {
  MockItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> createItem(_i4.Item? item) =>
      (super.noSuchMethod(
            Invocation.method(#createItem, [item]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createItem, [item]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<_i4.Item?> getItemById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getItemById, [id]),
            returnValue: _i3.Future<_i4.Item?>.value(),
          )
          as _i3.Future<_i4.Item?>);

  @override
  _i3.Future<List<_i4.Item>> getItems({
    String? categoryId,
    String? locationId,
    bool? includeUnlocated = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getItems, [], {
              #categoryId: categoryId,
              #locationId: locationId,
              #includeUnlocated: includeUnlocated,
            }),
            returnValue: _i3.Future<List<_i4.Item>>.value(<_i4.Item>[]),
          )
          as _i3.Future<List<_i4.Item>>);

  @override
  _i3.Future<List<_i4.Item>> getItemsByCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsByCategory, [categoryId]),
            returnValue: _i3.Future<List<_i4.Item>>.value(<_i4.Item>[]),
          )
          as _i3.Future<List<_i4.Item>>);

  @override
  _i3.Future<List<_i4.Item>> getItemsByLocation(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsByLocation, [locationId]),
            returnValue: _i3.Future<List<_i4.Item>>.value(<_i4.Item>[]),
          )
          as _i3.Future<List<_i4.Item>>);

  @override
  _i3.Future<List<_i4.Item>> searchItems(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchItems, [query]),
            returnValue: _i3.Future<List<_i4.Item>>.value(<_i4.Item>[]),
          )
          as _i3.Future<List<_i4.Item>>);

  @override
  _i3.Future<void> updateItem(_i4.Item? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteItem(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItem, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Item>> getExpiringItems(int? daysThreshold) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiringItems, [daysThreshold]),
            returnValue: _i3.Future<List<_i4.Item>>.value(<_i4.Item>[]),
          )
          as _i3.Future<List<_i4.Item>>);
}
