// Mocks generated by Mockito 5.4.6 from annotations
// in home_ai_index/test/unit/data/services/recognition_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:home_ai_index/data/models/api_credentials.dart' as _i6;
import 'package:home_ai_index/data/models/cloud_vision_request.dart' as _i5;
import 'package:home_ai_index/data/models/cloud_vision_response.dart' as _i2;
import 'package:home_ai_index/data/services/cloud_vision_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCloudVisionResponse_0 extends _i1.SmartFake
    implements _i2.CloudVisionResponse {
  _FakeCloudVisionResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CloudVisionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudVisionService extends _i1.Mock
    implements _i3.CloudVisionService {
  MockCloudVisionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CloudVisionResponse> recognizeImage(
    _i5.CloudVisionRequest? request,
    _i6.APICredentials? credentials,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recognizeImage, [request, credentials]),
            returnValue: _i4.Future<_i2.CloudVisionResponse>.value(
              _FakeCloudVisionResponse_0(
                this,
                Invocation.method(#recognizeImage, [request, credentials]),
              ),
            ),
          )
          as _i4.Future<_i2.CloudVisionResponse>);
}
