// Mocks generated by Mockito 5.4.6 from annotations
// in home_ai_index/test/widget/widgets/location_picker_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:home_ai_index/data/models/location.dart' as _i3;
import 'package:home_ai_index/presentation/viewmodels/locations_viewmodel.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocationsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationsViewModel extends _i1.Mock
    implements _i2.LocationsViewModel {
  MockLocationsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  List<_i3.Location> get locations =>
      (super.noSuchMethod(
            Invocation.getter(#locations),
            returnValue: <_i3.Location>[],
          )
          as List<_i3.Location>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadLocations({bool? rootOnly = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadLocations, [], {#rootOnly: rootOnly}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadChildLocations(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#loadChildLocations, [parentId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createLocation(String? name, String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#createLocation, [name, parentId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateLocation(String? id, String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocation, [id, newName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteLocation(String? id, {required bool? deleteItems}) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteLocation,
              [id],
              {#deleteItems: deleteItems},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> restoreLocation() =>
      (super.noSuchMethod(
            Invocation.method(#restoreLocation, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void clearUndoData() => super.noSuchMethod(
    Invocation.method(#clearUndoData, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> checkLocationHasItems(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#checkLocationHasItems, [locationId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i3.Location>> getLocationPath(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationPath, [locationId]),
            returnValue: _i4.Future<List<_i3.Location>>.value(<_i3.Location>[]),
          )
          as _i4.Future<List<_i3.Location>>);

  @override
  void selectLocation(_i3.Location? location) => super.noSuchMethod(
    Invocation.method(#selectLocation, [location]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSelection() => super.noSuchMethod(
    Invocation.method(#clearSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> validateLocationMove(
    String? locationId,
    String? newParentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateLocationMove, [locationId, newParentId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
