// Mocks generated by Mockito 5.4.6 from annotations
// in home_ai_index/test/widget/presentation/screens/add_item_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;
import 'dart:ui' as _i8;

import 'package:home_ai_index/data/models/category.dart' as _i3;
import 'package:home_ai_index/data/models/location.dart' as _i10;
import 'package:home_ai_index/presentation/viewmodels/add_item_viewmodel.dart'
    as _i2;
import 'package:home_ai_index/presentation/viewmodels/locations_viewmodel.dart'
    as _i9;
import 'package:image_picker/image_picker.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AddItemViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddItemViewModel extends _i1.Mock implements _i2.AddItemViewModel {
  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i3.Category> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: <_i3.Category>[],
            returnValueForMissingStub: <_i3.Category>[],
          )
          as List<_i3.Category>);

  @override
  _i2.RecognitionState get recognitionState =>
      (super.noSuchMethod(
            Invocation.getter(#recognitionState),
            returnValue: _i2.RecognitionState.idle,
            returnValueForMissingStub: _i2.RecognitionState.idle,
          )
          as _i2.RecognitionState);

  @override
  bool get hasApiCredentials =>
      (super.noSuchMethod(
            Invocation.getter(#hasApiCredentials),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get usedOnlineRecognition =>
      (super.noSuchMethod(
            Invocation.getter(#usedOnlineRecognition),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  int get quantity =>
      (super.noSuchMethod(
            Invocation.getter(#quantity),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get notes =>
      (super.noSuchMethod(
            Invocation.getter(#notes),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#notes),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#notes),
            ),
          )
          as String);

  @override
  String get suggestedName =>
      (super.noSuchMethod(
            Invocation.getter(#suggestedName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#suggestedName),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#suggestedName),
            ),
          )
          as String);

  @override
  List<String> get alternativeLabels =>
      (super.noSuchMethod(
            Invocation.getter(#alternativeLabels),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool get isLowConfidence =>
      (super.noSuchMethod(
            Invocation.getter(#isLowConfidence),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get recognitionSource =>
      (super.noSuchMethod(
            Invocation.getter(#recognitionSource),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#recognitionSource),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#recognitionSource),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> loadCategories() =>
      (super.noSuchMethod(
            Invocation.method(#loadCategories, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> pickImage(_i6.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [source]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recognizeImage(_i7.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#recognizeImage, [imageBytes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> retryRecognition() =>
      (super.noSuchMethod(
            Invocation.method(#retryRecognition, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> confirmQuotaAndRecognize() =>
      (super.noSuchMethod(
            Invocation.method(#confirmQuotaAndRecognize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void cancelQuotaWarning() => super.noSuchMethod(
    Invocation.method(#cancelQuotaWarning, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> refreshCredentialsStatus() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCredentialsStatus, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> saveItem() =>
      (super.noSuchMethod(
            Invocation.method(#saveItem, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void setName(String? value) => super.noSuchMethod(
    Invocation.method(#setName, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setCategory(String? value) => super.noSuchMethod(
    Invocation.method(#setCategory, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setLocation(String? value) => super.noSuchMethod(
    Invocation.method(#setLocation, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setQuantity(int? value) => super.noSuchMethod(
    Invocation.method(#setQuantity, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setNotes(String? value) => super.noSuchMethod(
    Invocation.method(#setNotes, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedImagePath(String? value) => super.noSuchMethod(
    Invocation.method(#setSelectedImagePath, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setErrorMessage(String? value) => super.noSuchMethod(
    Invocation.method(#setErrorMessage, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LocationsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationsViewModel extends _i1.Mock
    implements _i9.LocationsViewModel {
  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i10.Location> get locations =>
      (super.noSuchMethod(
            Invocation.getter(#locations),
            returnValue: <_i10.Location>[],
            returnValueForMissingStub: <_i10.Location>[],
          )
          as List<_i10.Location>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> loadLocations({bool? rootOnly = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadLocations, [], {#rootOnly: rootOnly}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadChildLocations(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#loadChildLocations, [parentId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> createLocation(String? name, String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#createLocation, [name, parentId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateLocation(String? id, String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocation, [id, newName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteLocation(String? id, {required bool? deleteItems}) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteLocation,
              [id],
              {#deleteItems: deleteItems},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> restoreLocation() =>
      (super.noSuchMethod(
            Invocation.method(#restoreLocation, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void clearUndoData() => super.noSuchMethod(
    Invocation.method(#clearUndoData, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> checkLocationHasItems(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#checkLocationHasItems, [locationId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i10.Location>> getLocationPath(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationPath, [locationId]),
            returnValue: _i5.Future<List<_i10.Location>>.value(
              <_i10.Location>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i10.Location>>.value(
              <_i10.Location>[],
            ),
          )
          as _i5.Future<List<_i10.Location>>);

  @override
  void selectLocation(_i10.Location? location) => super.noSuchMethod(
    Invocation.method(#selectLocation, [location]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSelection() => super.noSuchMethod(
    Invocation.method(#clearSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> validateLocationMove(
    String? locationId,
    String? newParentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateLocationMove, [locationId, newParentId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
