// Mocks generated by Mockito 5.4.6 from annotations
// in home_ai_index/test/widget/presentation/screens/item_details_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:home_ai_index/data/models/location_history.dart' as _i3;
import 'package:home_ai_index/presentation/viewmodels/item_details_viewmodel.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ItemDetailsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemDetailsViewModel extends _i1.Mock
    implements _i2.ItemDetailsViewModel {
  MockItemDetailsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  List<_i3.LocationHistory> get locationHistory =>
      (super.noSuchMethod(
            Invocation.getter(#locationHistory),
            returnValue: <_i3.LocationHistory>[],
          )
          as List<_i3.LocationHistory>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadItem() =>
      (super.noSuchMethod(
            Invocation.method(#loadItem, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadLocationHistory() =>
      (super.noSuchMethod(
            Invocation.method(#loadLocationHistory, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateItemName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateItemName, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateItemQuantity(int? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateItemQuantity, [quantity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateItemNotes(String? notes) =>
      (super.noSuchMethod(
            Invocation.method(#updateItemNotes, [notes]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateItemLocation(String? newLocationId) =>
      (super.noSuchMethod(
            Invocation.method(#updateItemLocation, [newLocationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateItemCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#updateItemCategory, [categoryId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> deleteItem() =>
      (super.noSuchMethod(
            Invocation.method(#deleteItem, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> restoreItem() =>
      (super.noSuchMethod(
            Invocation.method(#restoreItem, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void clearUndoData() => super.noSuchMethod(
    Invocation.method(#clearUndoData, []),
    returnValueForMissingStub: null,
  );

  @override
  String getLocationName(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationName, [locationId]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getLocationName, [locationId]),
            ),
          )
          as String);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
