// Mocks generated by Mockito 5.4.6 from annotations
// in home_ai_index/test/unit/presentation/viewmodels/add_item_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i11;

import 'package:home_ai_index/data/models/category.dart' as _i9;
import 'package:home_ai_index/data/models/image_recognition_result.dart' as _i2;
import 'package:home_ai_index/data/models/item.dart' as _i6;
import 'package:home_ai_index/data/repositories/category_repository.dart'
    as _i8;
import 'package:home_ai_index/data/repositories/image_repository.dart' as _i10;
import 'package:home_ai_index/data/repositories/item_repository.dart' as _i4;
import 'package:home_ai_index/data/services/image_recognition_service.dart'
    as _i12;
import 'package:image_picker/image_picker.dart' as _i13;
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImageRecognitionResult_0 extends _i1.SmartFake
    implements _i2.ImageRecognitionResult {
  _FakeImageRecognitionResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLostDataResponse_1 extends _i1.SmartFake
    implements _i3.LostDataResponse {
  _FakeLostDataResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemRepository extends _i1.Mock implements _i4.ItemRepository {
  MockItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> createItem(_i6.Item? item) =>
      (super.noSuchMethod(
            Invocation.method(#createItem, [item]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#createItem, [item]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i6.Item?> getItemById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getItemById, [id]),
            returnValue: _i5.Future<_i6.Item?>.value(),
          )
          as _i5.Future<_i6.Item?>);

  @override
  _i5.Future<List<_i6.Item>> getItems() =>
      (super.noSuchMethod(
            Invocation.method(#getItems, []),
            returnValue: _i5.Future<List<_i6.Item>>.value(<_i6.Item>[]),
          )
          as _i5.Future<List<_i6.Item>>);

  @override
  _i5.Future<List<_i6.Item>> getItemsByCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsByCategory, [categoryId]),
            returnValue: _i5.Future<List<_i6.Item>>.value(<_i6.Item>[]),
          )
          as _i5.Future<List<_i6.Item>>);

  @override
  _i5.Future<List<_i6.Item>> getItemsByLocation(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsByLocation, [locationId]),
            returnValue: _i5.Future<List<_i6.Item>>.value(<_i6.Item>[]),
          )
          as _i5.Future<List<_i6.Item>>);

  @override
  _i5.Future<List<_i6.Item>> searchItems(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchItems, [query]),
            returnValue: _i5.Future<List<_i6.Item>>.value(<_i6.Item>[]),
          )
          as _i5.Future<List<_i6.Item>>);

  @override
  _i5.Future<void> updateItem(_i6.Item? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [item]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteItem(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItem, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Item>> getExpiringItems(int? daysThreshold) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiringItems, [daysThreshold]),
            returnValue: _i5.Future<List<_i6.Item>>.value(<_i6.Item>[]),
          )
          as _i5.Future<List<_i6.Item>>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i8.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i9.Category>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i5.Future<List<_i9.Category>>.value(<_i9.Category>[]),
          )
          as _i5.Future<List<_i9.Category>>);

  @override
  _i5.Future<_i9.Category?> getCategoryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue: _i5.Future<_i9.Category?>.value(),
          )
          as _i5.Future<_i9.Category?>);

  @override
  _i5.Future<String> createCategory(_i9.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#createCategory, [category]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#createCategory, [category]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> updateCategory(_i9.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [category]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ImageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageRepository extends _i1.Mock implements _i10.ImageRepository {
  MockImageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> saveImage(_i11.Uint8List? imageBytes, String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#saveImage, [imageBytes, itemId]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#saveImage, [imageBytes, itemId]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i11.Uint8List> generateThumbnail(_i11.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#generateThumbnail, [imageBytes]),
            returnValue: _i5.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
          )
          as _i5.Future<_i11.Uint8List>);

  @override
  _i5.Future<_i11.Uint8List> compressImage(_i11.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#compressImage, [imageBytes]),
            returnValue: _i5.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
          )
          as _i5.Future<_i11.Uint8List>);

  @override
  _i5.Future<String> getImagePath(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#getImagePath, [itemId]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getImagePath, [itemId]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> deleteImage(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [imagePath]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> imageExists(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#imageExists, [imagePath]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [ImageRecognitionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageRecognitionService extends _i1.Mock
    implements _i12.ImageRecognitionService {
  MockImageRecognitionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ImageRecognitionResult> classifyImage(
    _i11.Uint8List? imageBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#classifyImage, [imageBytes]),
            returnValue: _i5.Future<_i2.ImageRecognitionResult>.value(
              _FakeImageRecognitionResult_0(
                this,
                Invocation.method(#classifyImage, [imageBytes]),
              ),
            ),
          )
          as _i5.Future<_i2.ImageRecognitionResult>);

  @override
  String mapLabelToCategory(String? label) =>
      (super.noSuchMethod(
            Invocation.method(#mapLabelToCategory, [label]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#mapLabelToCategory, [label]),
            ),
          )
          as String);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i13.ImagePicker {
  MockImagePicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.XFile?> pickImage({
    required _i3.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i3.CameraDevice? preferredCameraDevice = _i3.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [], {
              #source: source,
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #preferredCameraDevice: preferredCameraDevice,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i5.Future<_i3.XFile?>.value(),
          )
          as _i5.Future<_i3.XFile?>);

  @override
  _i5.Future<List<_i3.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiImage, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i5.Future<List<_i3.XFile>>.value(<_i3.XFile>[]),
          )
          as _i5.Future<List<_i3.XFile>>);

  @override
  _i5.Future<_i3.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i5.Future<_i3.XFile?>.value(),
          )
          as _i5.Future<_i3.XFile?>);

  @override
  _i5.Future<List<_i3.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultipleMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i5.Future<List<_i3.XFile>>.value(<_i3.XFile>[]),
          )
          as _i5.Future<List<_i3.XFile>>);

  @override
  _i5.Future<_i3.XFile?> pickVideo({
    required _i3.ImageSource? source,
    _i3.CameraDevice? preferredCameraDevice = _i3.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickVideo, [], {
              #source: source,
              #preferredCameraDevice: preferredCameraDevice,
              #maxDuration: maxDuration,
            }),
            returnValue: _i5.Future<_i3.XFile?>.value(),
          )
          as _i5.Future<_i3.XFile?>);

  @override
  _i5.Future<List<_i3.XFile>> pickMultiVideo({
    Duration? maxDuration,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiVideo, [], {
              #maxDuration: maxDuration,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i3.XFile>>.value(<_i3.XFile>[]),
          )
          as _i5.Future<List<_i3.XFile>>);

  @override
  _i5.Future<_i3.LostDataResponse> retrieveLostData() =>
      (super.noSuchMethod(
            Invocation.method(#retrieveLostData, []),
            returnValue: _i5.Future<_i3.LostDataResponse>.value(
              _FakeLostDataResponse_1(
                this,
                Invocation.method(#retrieveLostData, []),
              ),
            ),
          )
          as _i5.Future<_i3.LostDataResponse>);

  @override
  bool supportsImageSource(_i3.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#supportsImageSource, [source]),
            returnValue: false,
          )
          as bool);
}
