// Mocks generated by Mockito 5.4.6 from annotations
// in home_ai_index/test/unit/presentation/viewmodels/locations_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:home_ai_index/data/models/location.dart' as _i2;
import 'package:home_ai_index/data/repositories/location_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocation_0 extends _i1.SmartFake implements _i2.Location {
  _FakeLocation_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i3.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Location>> getLocations({bool? rootOnly = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getLocations, [], {#rootOnly: rootOnly}),
            returnValue: _i4.Future<List<_i2.Location>>.value(<_i2.Location>[]),
          )
          as _i4.Future<List<_i2.Location>>);

  @override
  _i4.Future<_i2.Location> getLocationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationById, [id]),
            returnValue: _i4.Future<_i2.Location>.value(
              _FakeLocation_0(this, Invocation.method(#getLocationById, [id])),
            ),
          )
          as _i4.Future<_i2.Location>);

  @override
  _i4.Future<List<_i2.Location>> getChildLocations(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#getChildLocations, [parentId]),
            returnValue: _i4.Future<List<_i2.Location>>.value(<_i2.Location>[]),
          )
          as _i4.Future<List<_i2.Location>>);

  @override
  _i4.Future<List<_i2.Location>> getLocationPath(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationPath, [locationId]),
            returnValue: _i4.Future<List<_i2.Location>>.value(<_i2.Location>[]),
          )
          as _i4.Future<List<_i2.Location>>);

  @override
  _i4.Future<_i2.Location> createLocation(_i2.Location? location) =>
      (super.noSuchMethod(
            Invocation.method(#createLocation, [location]),
            returnValue: _i4.Future<_i2.Location>.value(
              _FakeLocation_0(
                this,
                Invocation.method(#createLocation, [location]),
              ),
            ),
          )
          as _i4.Future<_i2.Location>);

  @override
  _i4.Future<_i2.Location> updateLocation(_i2.Location? location) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocation, [location]),
            returnValue: _i4.Future<_i2.Location>.value(
              _FakeLocation_0(
                this,
                Invocation.method(#updateLocation, [location]),
              ),
            ),
          )
          as _i4.Future<_i2.Location>);

  @override
  _i4.Future<bool> deleteLocation(String? id, {bool? deleteItems = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteLocation,
              [id],
              {#deleteItems: deleteItems},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasItems(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#hasItems, [locationId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> validateLocationMove(
    String? locationId,
    String? newParentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateLocationMove, [locationId, newParentId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
