// Mocks generated by Mockito 5.4.6 from annotations
// in home_ai_index/test/integration/cloud_vision_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:convert' as _i5;
import 'dart:typed_data' as _i7;

import 'package:home_ai_index/data/models/api_log_entry.dart' as _i8;
import 'package:home_ai_index/data/services/api_usage_logger.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAPIUsageStats_2 extends _i1.SmartFake implements _i3.APIUsageStats {
  _FakeAPIUsageStats_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i5.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i7.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i4.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
          )
          as _i4.Future<_i7.Uint8List>);

  @override
  _i4.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i4.Future<_i2.StreamedResponse>.value(
              _FakeStreamedResponse_1(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [APIUsageLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIUsageLogger extends _i1.Mock implements _i3.APIUsageLogger {
  MockAPIUsageLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i8.APILogEntry> get logStream =>
      (super.noSuchMethod(
            Invocation.getter(#logStream),
            returnValue: _i4.Stream<_i8.APILogEntry>.empty(),
          )
          as _i4.Stream<_i8.APILogEntry>);

  @override
  _i4.Future<void> logApiCall(_i8.APILogEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#logApiCall, [entry]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logSuccess({
    required String? endpoint,
    required int? statusCode,
    required Duration? latency,
    int? imageSize,
    int? labelsReturned,
    String? requestId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSuccess, [], {
              #endpoint: endpoint,
              #statusCode: statusCode,
              #latency: latency,
              #imageSize: imageSize,
              #labelsReturned: labelsReturned,
              #requestId: requestId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logFailure({
    required String? endpoint,
    int? statusCode,
    Duration? latency,
    required String? error,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logFailure, [], {
              #endpoint: endpoint,
              #statusCode: statusCode,
              #latency: latency,
              #error: error,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.APILogEntry>> getLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getLogs, []),
            returnValue: _i4.Future<List<_i8.APILogEntry>>.value(
              <_i8.APILogEntry>[],
            ),
          )
          as _i4.Future<List<_i8.APILogEntry>>);

  @override
  _i4.Future<List<_i8.APILogEntry>> getLogsByDateRange({
    required DateTime? start,
    required DateTime? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLogsByDateRange, [], {
              #start: start,
              #end: end,
            }),
            returnValue: _i4.Future<List<_i8.APILogEntry>>.value(
              <_i8.APILogEntry>[],
            ),
          )
          as _i4.Future<List<_i8.APILogEntry>>);

  @override
  _i4.Future<List<_i8.APILogEntry>> getTodaysLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysLogs, []),
            returnValue: _i4.Future<List<_i8.APILogEntry>>.value(
              <_i8.APILogEntry>[],
            ),
          )
          as _i4.Future<List<_i8.APILogEntry>>);

  @override
  _i4.Future<List<_i8.APILogEntry>> getMonthLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getMonthLogs, []),
            returnValue: _i4.Future<List<_i8.APILogEntry>>.value(
              <_i8.APILogEntry>[],
            ),
          )
          as _i4.Future<List<_i8.APILogEntry>>);

  @override
  _i3.APIUsageStats getStats(List<_i8.APILogEntry>? logs) =>
      (super.noSuchMethod(
            Invocation.method(#getStats, [logs]),
            returnValue: _FakeAPIUsageStats_2(
              this,
              Invocation.method(#getStats, [logs]),
            ),
          )
          as _i3.APIUsageStats);

  @override
  _i4.Future<_i3.APIUsageStats> getTodaysStats() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysStats, []),
            returnValue: _i4.Future<_i3.APIUsageStats>.value(
              _FakeAPIUsageStats_2(
                this,
                Invocation.method(#getTodaysStats, []),
              ),
            ),
          )
          as _i4.Future<_i3.APIUsageStats>);

  @override
  _i4.Future<_i3.APIUsageStats> getMonthStats() =>
      (super.noSuchMethod(
            Invocation.method(#getMonthStats, []),
            returnValue: _i4.Future<_i3.APIUsageStats>.value(
              _FakeAPIUsageStats_2(this, Invocation.method(#getMonthStats, [])),
            ),
          )
          as _i4.Future<_i3.APIUsageStats>);

  @override
  _i4.Future<void> clearLogs() =>
      (super.noSuchMethod(
            Invocation.method(#clearLogs, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearOldLogs(int? daysToKeep) =>
      (super.noSuchMethod(
            Invocation.method(#clearOldLogs, [daysToKeep]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
