// Mocks generated by Mockito 5.4.6 from annotations
// in home_ai_index/test/integration/user_story_4_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:home_ai_index/data/models/category.dart' as _i8;
import 'package:home_ai_index/data/models/item.dart' as _i5;
import 'package:home_ai_index/data/models/location.dart' as _i2;
import 'package:home_ai_index/data/repositories/category_repository.dart'
    as _i7;
import 'package:home_ai_index/data/repositories/item_repository.dart' as _i3;
import 'package:home_ai_index/data/repositories/location_repository.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocation_0 extends _i1.SmartFake implements _i2.Location {
  _FakeLocation_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemRepository extends _i1.Mock implements _i3.ItemRepository {
  MockItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> createItem(_i5.Item? item) =>
      (super.noSuchMethod(
            Invocation.method(#createItem, [item]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createItem, [item]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i5.Item?> getItemById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getItemById, [id]),
            returnValue: _i4.Future<_i5.Item?>.value(),
          )
          as _i4.Future<_i5.Item?>);

  @override
  _i4.Future<List<_i5.Item>> getItems({
    String? categoryId,
    String? locationId,
    bool? includeUnlocated = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getItems, [], {
              #categoryId: categoryId,
              #locationId: locationId,
              #includeUnlocated: includeUnlocated,
            }),
            returnValue: _i4.Future<List<_i5.Item>>.value(<_i5.Item>[]),
          )
          as _i4.Future<List<_i5.Item>>);

  @override
  _i4.Future<List<_i5.Item>> getItemsByCategory(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsByCategory, [categoryId]),
            returnValue: _i4.Future<List<_i5.Item>>.value(<_i5.Item>[]),
          )
          as _i4.Future<List<_i5.Item>>);

  @override
  _i4.Future<List<_i5.Item>> getItemsByLocation(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsByLocation, [locationId]),
            returnValue: _i4.Future<List<_i5.Item>>.value(<_i5.Item>[]),
          )
          as _i4.Future<List<_i5.Item>>);

  @override
  _i4.Future<List<_i5.Item>> searchItems(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchItems, [query]),
            returnValue: _i4.Future<List<_i5.Item>>.value(<_i5.Item>[]),
          )
          as _i4.Future<List<_i5.Item>>);

  @override
  _i4.Future<void> updateItem(_i5.Item? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteItem(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItem, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Item>> getExpiringItems(int? daysThreshold) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiringItems, [daysThreshold]),
            returnValue: _i4.Future<List<_i5.Item>>.value(<_i5.Item>[]),
          )
          as _i4.Future<List<_i5.Item>>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i7.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i8.Category>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i4.Future<List<_i8.Category>>.value(<_i8.Category>[]),
          )
          as _i4.Future<List<_i8.Category>>);

  @override
  _i4.Future<_i8.Category?> getCategoryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue: _i4.Future<_i8.Category?>.value(),
          )
          as _i4.Future<_i8.Category?>);

  @override
  _i4.Future<String> createCategory(_i8.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#createCategory, [category]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createCategory, [category]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> updateCategory(_i8.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [category]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i9.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Location>> getLocations({bool? rootOnly = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getLocations, [], {#rootOnly: rootOnly}),
            returnValue: _i4.Future<List<_i2.Location>>.value(<_i2.Location>[]),
          )
          as _i4.Future<List<_i2.Location>>);

  @override
  _i4.Future<_i2.Location> getLocationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationById, [id]),
            returnValue: _i4.Future<_i2.Location>.value(
              _FakeLocation_0(this, Invocation.method(#getLocationById, [id])),
            ),
          )
          as _i4.Future<_i2.Location>);

  @override
  _i4.Future<List<_i2.Location>> getChildLocations(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#getChildLocations, [parentId]),
            returnValue: _i4.Future<List<_i2.Location>>.value(<_i2.Location>[]),
          )
          as _i4.Future<List<_i2.Location>>);

  @override
  _i4.Future<List<_i2.Location>> getLocationPath(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocationPath, [locationId]),
            returnValue: _i4.Future<List<_i2.Location>>.value(<_i2.Location>[]),
          )
          as _i4.Future<List<_i2.Location>>);

  @override
  _i4.Future<_i2.Location> createLocation(_i2.Location? location) =>
      (super.noSuchMethod(
            Invocation.method(#createLocation, [location]),
            returnValue: _i4.Future<_i2.Location>.value(
              _FakeLocation_0(
                this,
                Invocation.method(#createLocation, [location]),
              ),
            ),
          )
          as _i4.Future<_i2.Location>);

  @override
  _i4.Future<_i2.Location> updateLocation(_i2.Location? location) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocation, [location]),
            returnValue: _i4.Future<_i2.Location>.value(
              _FakeLocation_0(
                this,
                Invocation.method(#updateLocation, [location]),
              ),
            ),
          )
          as _i4.Future<_i2.Location>);

  @override
  _i4.Future<bool> deleteLocation(String? id, {bool? deleteItems = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteLocation,
              [id],
              {#deleteItems: deleteItems},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasItems(String? locationId) =>
      (super.noSuchMethod(
            Invocation.method(#hasItems, [locationId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> validateLocationMove(
    String? locationId,
    String? newParentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateLocationMove, [locationId, newParentId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
